name: Transcendence Local
values:
  - key: base_url
    value: 'https://poolaki.localhost'
  - key: csrf_token
    value: ''
  - key: is_authenticated
    value: ''
  - key: current_user_id
    value: ''
  - key: current_username
    value: ''
  - key: current_email
    value: ''
  - key: session_id
    value: ''
