apiVersion: 1

policies:
  - orgId: 1
    receiver: email-contact-point
    group_by: ['grafana_folder', 'alertname']
    routes:
      - receiver: email-contact-point
        object_matchers:
          - ['severity', '=', 'critical']
        continue: false