# Generated by Django 6.0.6 on 2026-09-14 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('transaction_added', 'Transaction added'), ('goal_completed', 'Goal completed'), ('member_left', 'Member left'), ('member_removed', 'Member removed'), ('removed_from_org', 'Removed from org'), ('organization_deleted', 'Organization deleted')], max_length=30),
        ),
    ]
