# Generated by Django 6.0.6 on 2026-09-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('transaction_added', 'Transaction added'), ('goal_completed', 'Goal completed'), ('member_left', 'Member left'), ('ownership_transferred', 'Ownership transferred')], max_length=30),
        ),
    ]
