# Generated by Django 6.0.6 on 2026-09-06 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_activitylog_action_alter_category_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('contribution', 'Contribution')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='entry_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('contribution', 'Contribution')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('org', 'name', 'type'), name='unique_category_per_org'),
        ),
    ]
