# Generated by Django 6.0.6 on 2026-10-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_default_categories'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['org_id', 'transaction_date'], name='core_transa_org_id_08a4de_idx'),
        ),
    ]
