# Generated by Django 6.0.6 on 2026-09-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_default_categories'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['org', 'transaction_date'], name='idx_txn_org_date'),
        ),
    ]
