# Generated by Django 6.0.6 on 2026-10-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaction_idx_txn_org_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='completed_at',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='entry_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('contribution', 'Contribution'), ('withdraw', 'Withdraw')], max_length=20),
        ),
    ]
